In [1]:
#Import library yang diperlukan
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#import dataset IRIS dari alamat yang terletak di github
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')
X = dataset.iloc[:,:4].values
y = dataset['species'].values
dataset.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
#untuk menampilkan jumlah baris
len (y)


dataset.head(150)

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [11]:
#menampilkan seluruh data x dan y
print (y)
print (X)

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

In [5]:
#split data ke training set dan test set 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [6]:
#kemudian dataset di perkecil lagi menggunakan opsi feature scaling. Dalam hal ini, nilai X_train dan X_test diperkecil ke nilai yang lebih kecil untuk meningkatkan kecepatan program.
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
#menampilkan X_train dan X_test
print (X_train)
print (x_test)

[[ 1.60353508e+00 -1.58790550e-01  1.15243322e+00  5.32261979e-01]
 [ 7.59569247e-01 -1.58790550e-01  8.09560525e-01  1.06563515e+00]
 [ 6.39002700e-01  6.27776591e-02  9.80996872e-01  7.98948566e-01]
 [-2.04963130e-01 -1.26663159e+00  6.95269627e-01  1.06563515e+00]
 [ 2.77303058e-01 -1.04506338e+00  1.03814232e+00  2.65575392e-01]
 [ 1.00070234e+00  6.27776591e-02  5.23833281e-01  3.98918686e-01]
 [-1.53119515e+00  1.17061870e+00 -1.59054833e+00 -1.33454413e+00]
 [-2.04963130e-01  1.61375512e+00 -1.19053018e+00 -1.20120083e+00]
 [-9.28362413e-01  1.61375512e+00 -1.07623929e+00 -1.06785754e+00]
 [-2.04963130e-01  2.94316437e+00 -1.30482108e+00 -1.06785754e+00]
 [ 5.18436152e-01 -1.26663159e+00  6.95269627e-01  9.32291859e-01]
 [-1.16949551e+00  6.27776591e-02 -1.30482108e+00 -1.46788742e+00]
 [-2.04963130e-01 -6.01926967e-01  4.09542383e-01  1.32232099e-01]
 [-1.04892896e+00 -1.70976801e+00 -2.76203003e-01 -2.67797781e-01]
 [ 1.60353508e+00  2.84345868e-01  1.26672412e+00  7.98948566e

NameError: name 'x_test' is not defined

In [12]:
#melakukan klasifikasi data set menggunakan algoritma naive bayes.
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [9]:
#X_train di prediksi dan dimasukan ke variable y_pred
y_pred = classifier.predict(X_test) 
y_pred

array(['virginica', 'virginica', 'virginica', 'virginica', 'setosa',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'setosa',
       'virginica', 'virginica', 'versicolor', 'setosa', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'versicolor', 'setosa', 'versicolor', 'setosa', 'virginica',
       'setosa', 'setosa', 'virginica', 'virginica', 'virginica'],
      dtype='<U10')

In [10]:
#akurasinya menggunakan sklearn.metrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  0.9333333333333333


array([[11,  0,  0],
       [ 0,  8,  1],
       [ 0,  1,  9]], dtype=int64)